/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.2 Strawberry_gltf.gltf
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Model(props) {
  const { nodes, materials } = useGLTF('/Strawberry_gltf.gltf')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.strawberry.geometry} material={materials.Strawberry} rotation={[-0.05, -1.23, 1.54]} scale={1.22} />
    </group>
  )
}

useGLTF.preload('/Strawberry_gltf.gltf')
